# Generated by Django 6.0.4 on 2026-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, help_text='Descripción breve para los listados', max_length=255),
        ),
    ]
